[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
node_linear1_weight = { path = "../initializers/node_linear1_weight"} 
node_linear1_bias = { path = "../initializers/node_linear1_bias"} 
node_linear2_weight = { path = "../initializers/node_linear2_weight"} 
node_linear2_bias = { path = "../initializers/node_linear2_bias"} 
node_linear3_weight = { path = "../initializers/node_linear3_weight"} 
node_linear3_bias = { path = "../initializers/node_linear3_bias"} 
_constant_value = { path = "../attributes/_constant_value"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "7d84a42" } 
[lib]
sierra-text = true